name: Frontend Tests

on:
  push:
    branches: [ feature/* ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'
  pull_request:
    branches: [ feature/* ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'

jobs:
  test-frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Vitest tests
        run: npm test
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: frontend/coverage
          retention-days: 5 