name: RAG System Tests

on:
  push:
    branches: [ feature/* ]
    paths:
      - 'rag/**'
      - '.github/workflows/rag-test.yml'
  pull_request:
    branches: [ feature/* ]
    paths:
      - 'rag/**'
      - '.github/workflows/rag-test.yml'

jobs:
  test-rag:
    name: Run RAG System Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
          pip install -r requirements.txt
      
      - name: Run pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HELICONE_API_KEY: ${{ secrets.HELICONE_API_KEY }}
        run: |
          pytest rag/tests/ -v
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rag-test-results
          path: |
            rag/tests/reports/
            rag/tests/.coverage
          retention-days: 5 