name: Enforce Semantic Versioning for Release Branches

on:
  push:
    branches:
      - "release/*"

jobs:
  check-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name follows Semantic Versioning
        run: |
          # Get the branch name
          BRANCH_NAME="${{ github.ref }}"

          # Extract the release version part (e.g., 'release/2.1.3')
          VERSION_PART="${BRANCH_NAME#refs/heads/release/}"

          # Regular expression to match Semantic Versioning format: MAJOR.MINOR.PATCH
          SEMVER_REGEX="^[0-9]+\.[0-9]+\.[0-9]+$"

          # Check if the version part matches the SemVer format
          if [[ ! "$VERSION_PART" =~ $SEMVER_REGEX ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not follow Semantic Versioning (SemVer)."
            echo "Branch names must follow the format: release/{MAJOR}.{MINOR}.{PATCH}."
            exit 1
          else
            echo "Branch name '$BRANCH_NAME' follows Semantic Versioning."
          fi
